# Runs tolerant-php-parser's tests
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
    strategy:
      fail-fast: false
      matrix:
       include:
         # NOTE: If this is not quoted, the yaml parser will convert numbers such as 8.0 to the number 8,
         # and the docker image `php:8` is the latest minor version of php 8.x (8.1).
         - PHP_VERSION: '7.2'
           STATIC_ANALYSIS: true
         - PHP_VERSION: '7.3'
         - PHP_VERSION: '7.4'
         - PHP_VERSION: '8.0'
         - PHP_VERSION: '8.1'
         - PHP_VERSION: '8.2.0beta2'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Clone submodules
      - name: Checkout submodules for validation tests
        run: git submodule update --init --recursive --depth 1

      # Runs a single command using the runners shell
      - name: Build and test in docker
        run: bash ci/run_tests_dockerized.sh ${{ matrix.PHP_VERSION }}

      - name: Run static analysis (PHP 7.2 only)
        run: if [[ "${{ matrix.STATIC_ANALYSIS }}" == true ]]; then bash ci/run_phpstan_dockerized.sh ${{ matrix.PHP_VERSION }}; fi
